version: '3.8'
services:

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=trabalho-poo
      - POSTGRES_USER=trabalho-poo
      - POSTGRES_PASSWORD=trabalho-poo
      - MAX_CONNECTIONS=300